<?xml version="1.0" encoding="UTF-8"?>
<tusar:tusar xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:t="http://www.thalesgroup.com/tusar/tests/v3"
             xmlns:tusar="http://www.thalesgroup.com/tusar/v3"
             version="3.0">
    <tusar:tests toolname="phpunit">
        <t:testsuite name="DataTest::testAdd" tests="4" failures="1" errors="0" skipped="" time="0.016757" timestamp="">
            <t:testcase testname="testAdd with data set #0" time="0.003837" assertions="1"/>
            <t:testcase testname="testAdd with data set #1" time="0.003892" assertions="1"/>
            <t:testcase testname="testAdd with data set #2" time="0.003831" assertions="1"/>
            <t:testcase testname="testAdd with data set #3" time="0.005197" assertions="1">
                <t:failure message="" type="PHPUnit_Framework_ExpectationFailedException">DataTest::testAdd with data
                    set #3 (1, 1, 3)
                    Failed asserting that &lt;integer:2&gt; matches expected &lt;integer:3&gt;.

                    C:\Documents and Settings\thales\Mes documents\www\htdocs\phpUnit\DataTest.php:9
                </t:failure>
            </t:testcase>
        </t:testsuite>
    </tusar:tests>
</tusar:tusar>